# Commands Prefix
# Delay between commands
# Its recommended to set this to 10 seconds or higher

commands: {
  prefix: '!',
  delay: 30
}

# Set affected players
# all/permission
# all: All players will be affected
# permission: Only players with the permission (nl.corwindev.streamervschat.streamer) will be affected
affected-players: all

# Poison effect
# Set the duration of the poison effect
poison-duration: 20

# Blacklist
# Set the words that will be blacklisted
# If a player says one of these words, he will be denied
blacklist: []

# Cooldown
# Set the cooldown for the commands
# If a player uses a command, he will be denied for the set amount of seconds
cooldowns:
  dropall: 30
  drop: 30


# Hotbar message
# Set the message that will be displayed in the hotbar
# %player% will be replaced with the player's name
# %command% will be replaced with the command
hotbar: '§a§l%user%§r§a has executed the command: §l%command%'


# Discord Bot
# https://github.com/CorwinDev/StreamerVSChat/wiki#discord-setup
discord: {
  enabled: false,
  token: 'discord token',
  channel: 'channel id'
}

# Twitch Chat
# https://github.com/CorwinDev/StreamerVSChat/wiki#twitch-setup
twitch: {
  enabled: false,
  token: 'twitch token',
  channel: 'twitch channel' 
}

# Youtube Chat
# https://github.com/CorwinDev/StreamerVSChat/wiki#youtube-setup
youtube: {
  enabled: false,
  youtubeId: 'youtube id',
  apiKey: 'youtube api key'
}

# Custom Commands
#
# You can add custom commands to the plugin
# You can add as many commands as you want
# Command name without the prefix
# Command: Command that will be executed without the /
# You can use %player% to get the player name
# Example: !test -> /give %player% diamond 1

customcommands:
  'test':
    command: 'give %player% diamond 1'
    cooldown: 30
  'test2':
    command: 'give %player% diamond 2'