discord: {
  enabled: false,
  token: 'discord token', #Get your token from here: https://discord.dev
  channel: 'channel id'
}

twitch: {
  enabled: false,
  token: 'twitch token', #Get your token from here: https://twitchapps.com/tmi/
  channel: 'twitch channel' 
}

youtube: {
  enabled: false,
  youtubeId: 'youtube id',
  apiKey: 'youtube api key' # https://developers.google.com/youtube/v3/getting-started
}

commands: {
  prefix: '!',
  delay: 30 #Delay to check for new messages
}