discord: {
  enabled: false,
  token: 'discord token',
  channel: 'channel id'
}

twitch: {
  enabled: false,
  token: 'twitch token',
  channel: 'twitch channel' 
}

youtube: {
  enabled: false,
  youtubeId: 'youtube id',
  apiKey: 'youtube api key'
}

commands: {
  prefix: '!',
  delay: 30
}